use std::sync::Mutex;
use tauri::Manager;

mod history;
use history::{History, HistoryEntry};

struct State {
    next_entry_id: u32,
    history: History,
}

impl Default for State {
    fn default() -> Self {
        Self {
            next_entry_id: 1,
            history: History::new(),
        }
    }
}

impl State {
    pub fn reset(&mut self) {
        *self = Self::default();
    }

    pub fn insert_entry(&mut self, entry: keyring_core::Entry) -> HistoryEntry {
        let he = HistoryEntry::new_from_entry(self.next_entry_id, entry);
        self.next_entry_id += 1;
        self.history.insert(he.id.clone(), he.clone());
        he
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    #[allow(unused_qualifications)]
    tauri::Builder::default()
        .plugin(tauri_plugin_os::init())
        .setup(|app| {
            app.manage(Mutex::new(State::default()));
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            history::use_named_store,
            history::release_store,
            history::store_info,
            history::get_entry,
            history::get_all_entries,
            history::remove_entry,
            history::entry_new,
            history::entry_set_value,
            history::entry_get_value,
            history::entry_get_attributes,
            history::entry_update_attributes,
            history::entry_delete_value,
            history::search_all,
        ])
        .run(tauri::generate_context!())
        .expect("valueError while running tauri application");
}

/// Initialize the NDK context.
///
/// This JNI function prepares the NDK context for use by this crate.
/// (Tauri no longer does this for us.)
///
/// This function is called from the main activity's `onCreate` method,
/// which has to be altered after being generated by Tauri. It's defined
/// as part of the MainActivity class.
/// ```
#[cfg(target_os = "android")]
#[allow(non_snake_case)]
#[unsafe(no_mangle)]
pub extern "system" fn Java_com_brotsky_keyring_1demo_MainActivity_init_1ndk_1context(
    env: jni::JNIEnv,
    _class: jni::objects::JObject,
    context: jni::objects::JObject,
) {
    use std::ffi::c_void;
    use std::sync::{OnceLock};
    use jni::objects::GlobalRef;
    static REF: OnceLock<Option<GlobalRef>> = OnceLock::new();
    REF.get_or_init(|| match env.new_global_ref(&context) {
        Ok(ref_) => {
            let vm = env.get_java_vm().unwrap();
            let vm = vm.get_java_vm_pointer() as *mut c_void;
            unsafe {
                ndk_context::initialize_android_context(vm, ref_.as_obj().as_raw() as _);
            }
            Some(ref_)
        }
        Err(e) => {
            tracing::error!(%e, "error creating global reference for context");
            tracing::debug!(?e);
            None
        }
    });
}
