name: 'tauri-build'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  tauri-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm-based Macs (M1 and above)
            args: '--target aarch64-apple-darwin'
            name: 'macOS-aarch64'
          - platform: 'macos-latest' # for Intel-based Macs
            args: '--target x86_64-apple-darwin'
            name: 'macOS-x86_64'
          - platform: 'ubuntu-24.04'
            args: ''
            name: 'Ubuntu-24.04'
          - platform: 'ubuntu-24.04-arm'
            args: ''
            name: 'Ubuntu-24.04-arm'
          - platform: 'windows-latest'
            args: ''
            name: 'Windows-x86_64'
          - platform: 'windows-11-arm'
            args: ''
            name: 'Windows-arm'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-24.04' || matrix.platform == 'ubuntu-24.04-arm'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Import Code-Signing Certificates
        if: matrix.platform == 'macos-latest'
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_FILE_PASSWORD }}

      - name: Add Notarization Data
        if: matrix.platform == 'macos-latest'
        run: |
          echo "APPLE_ID=${{ secrets.NOTARIZATION_APPLE_ID }}" >> $GITHUB_ENV
          echo "APPLE_ID_PASSWORD=${{ secrets.NOTARIZATION_APPLE_ID_PASSWORD }}" >> $GITHUB_ENV
          echo "APPLE_TEAM_ID=${{ secrets.NOTARIZATION_APPLE_TEAM_ID }}" >> $GITHUB_ENV

      - name: install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        id: tauri_build
        with:
          tauriScript: 'npm run tauri'
          args: ${{ matrix.args }}

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: "${{ join(fromJSON(steps.tauri_build.outputs.artifactPaths), '\n') }}"
